-- ROLLBACK FOR PERFORMANCE OPTIMIZATION INDEXES

DROP INDEX IF EXISTS resident.idx_resident_session_ida_token;

DROP INDEX IF EXISTS resident.idx_resident_user_actions_ida_token;

-- END ROLLBACK FOR PERFORMANCE OPTIMIZATION INDEXES
