openapi: 3.0.1
info:
  title: Proxy Config API
  description: API for getting the identity mapping configuration
  version: 1.0.0
paths:
  /auth-proxy/config/identity-mapping:
    get:
      summary: getIdentityMapping
      description: Get the identity-mapping
      tags:
        - proxy-config-controller
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
                example: ''
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
                example: ''
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: string
                example: ''
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: string
                example: ''
