openapi: 3.1.0
x-stoplight:
  id: sroysh0ppi879
info:
  title: API to get the terms and conditions
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/auth-proxy​/masterdata​/templates/{langcode}/{templatetypecode}':
    parameters:
      - schema:
          type: string
        name: langcode
        in: path
        required: true
      - schema:
          type: string
        name: templatetypecode
        in: path
        required: true
    get:
      summary: '/auth-proxy​/masterdata​/templates/{langcode}/{templatetypecode}'
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: 'null'
                  version:
                    type: 'null'
                  responsetime:
                    type: string
                  metadata:
                    type: 'null'
                  response:
                    type: object
                    properties:
                      fileText:
                        type: string
                  errors:
                    type: 'null'
                x-examples:
                  example-1:
                    id: null
                    version: null
                    responsetime: '2022-07-25T12:04:40.669Z'
                    metadata: null
                    response:
                      fileText: |-
                        1. Your data will be shared with the chosen third party (credential partner)
                         2. You are responsible for any and all costs and fees associated with agreements entered into with the third-party provider.
                         3. Under no circumstances will we be liable for loss or misuse of data whatsoever, arising from the usage of data shared with the partner.
                         4. If a third-party provider ceases to make its service available or requires MOSIP to suspend or terminate the provision of all or any part of its services to you that part of data or services will be terminated immediately without notice or further obligation to you.
                    errors: null
              examples:
                Success:
                  value:
                    id: null
                    version: null
                    responsetime: '2022-07-25T12:04:40.669Z'
                    response:
                      fileText: |-
                        1. Your data will be shared with the chosen third party (credential partner)
                         2. You are responsible for any and all costs and fees associated with agreements entered into with the third-party provider.
                         3. Under no circumstances will we be liable for loss or misuse of data whatsoever, arising from the usage of data shared with the partner.
                         4. If a third-party provider ceases to make its service available or requires MOSIP to suspend or terminate the provision of all or any part of its services to you that part of data or services will be terminated immediately without notice or further obligation to you.
                    errors: null
                'Error: Template exception':
                  value:
                    id: null
                    version: null
                    responsetime: '2022-07-25T12:04:40.669Z'
                    response: null
                    errors:
                      - errorCode: RES-SER-415
                        message: Template exception
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Example 1:
                  value:
                    id: null
                    version: null
                    responsetime: '2022-10-07T09:22:03.631Z'
                    metadata: null
                    response: null
                    errors:
                      - errorCode: KER-ATH-401
                        message: Authentication Failed
      operationId: get-proxy-masterdata-templates-langcode-templatetypecode
      parameters:
        - schema:
            type: string
          in: cookie
          name: Authorization
          required: true
          description: Authorization token is used to validate the permissions carried by the user.
        - schema:
            type: string
          in: cookie
          description: Id token is used to verify which user has logged in.
          name: id_token
          required: true
      description: 'This API is to return terms and conditions for different use cases for different languages such as eng, fra, and ara. This will be invoked by UI for the specific language. This is a Proxy API of master data service for getting templates for template type code and language code . This should be an authenticated proxy API. '
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
