openapi: 3.1.0
x-stoplight:
  id: xq13gtyrp0o9h
info:
  title: API to order a physical card
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /resident/v1/sendCard:
    post:
      summary: /resident/v1/sendCard
      operationId: post-resident-v1-sendCard
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  version:
                    type: string
                  responsetime:
                    type: string
                  metadata:
                    type: 'null'
                  response:
                    type: object
                    properties:
                      id:
                        type: string
                      requestId:
                        type: string
                  errors:
                    type: 'null'
                x-examples:
                  example-1:
                    id: string
                    version: v1
                    responsetime: '2022-06-23T11:48:10.359Z'
                    metadata: null
                    response:
                      id: '8251649601'
                      requestId: 7256e703-3e76-4ed3-9d4d-076708605423
                    errors: null
              examples:
                Success:
                  value:
                    id: string
                    version: string
                    responsetime: string
                    metadata: null
                    response:
                      id: string
                      requestId: string
                    errors: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                request:
                  type: object
                  properties:
                    individualId:
                      type: string
                    transactionID:
                      type: string
                    issuer:
                      type: string
                requesttime:
                  type: string
                version:
                  type: string
              x-examples:
                example-1:
                  id: string
                  request:
                    individualId: '8251649601'
                    transactionID: '1234327890'
                    issuer: mpartner-default-print
                  requesttime: '2021-10-19T17:01:59.538Z'
                  version: v1
            examples:
              example-1:
                value:
                  id: string
                  request:
                    individualId: string
                    transactionID: string
                    issuer: string
                  requesttime: string
                  version: string
      description: 'This API is an authenticated API to send a card to print partner for the individual ID present in logged in session, and the transaction ID.'
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
