openapi: 3.1.0
x-stoplight:
  id: lmohj2mxxvd0m
info:
  title: API to invoke credential request for the customized format and masking for id attributes
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /req/credential-generator:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-req-credential-generator
    post:
      summary: /req/credential-generator
      operationId: post-req-credential-generator
      responses:
        '200':
          description: OK
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  version:
                    type: string
                  responsetime:
                    type: string
                  metadata:
                    type: 'null'
                  response:
                    type: object
                    properties:
                      id:
                        type: string
                      requestId:
                        type: string
                  errors:
                    type: 'null'
                x-examples:
                  example-1:
                    id: string
                    version: v1
                    responsetime: '2022-06-23T12:00:40.326Z'
                    metadata: null
                    response:
                      id: '8251649601'
                      requestId: 9002d4fe-5580-463c-8507-ad2fa07d19f9
                    errors: null
              examples:
                Success:
                  value:
                    id: string
                    version: string
                    responsetime: string
                    metadata: null
                    response:
                      id: string
                      requestId: string
                    errors: null
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                request:
                  type: object
                  properties:
                    additionalData:
                      type: object
                      properties: {}
                    credentialType:
                      type: string
                    encrypt:
                      type: boolean
                    encryptionKey:
                      type: string
                    individualId:
                      type: string
                    issuer:
                      type: string
                    recepiant:
                      type: string
                    sharableAttributes:
                      type: array
                      items:
                        type: object
                        properties:
                          attributeName:
                            type: string
                          format:
                            type: string
                          isMasked:
                            type: boolean
                    user:
                      type: string
                requesttime:
                  type: string
                version:
                  type: string
              x-examples:
                example-1:
                  id: string
                  request:
                    additionalData: {}
                    credentialType: euin
                    encrypt: true
                    encryptionKey: abc123
                    individualId: '8251649601'
                    issuer: mpartner-default-print
                    recepiant: ''
                    sharableAttributes:
                      - attributeName: dateOfBirth
                        format: YYYY
                        isMasked: false
                    user: string
                  requesttime: '2021-10-19T17:01:59.538Z'
                  version: v1
            examples:
              example-1:
                value:
                  id: string
                  request:
                    additionalData: {}
                    credentialType: string
                    encrypt: true
                    encryptionKey: string
                    individualId: string
                    issuer: string
                    recepiant: string
                    sharableAttributes:
                      - attributeName: string
                        format: string
                        isMasked: true
                    user: string
                  requesttime: string
                  version: string
      description: This is an authenticated API  to request for credentials with the additional input of attribute formats and masking information. This is used in requesting credentials to a selected partner.
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
