openapi: 3.1.0
x-stoplight:
  id: yjq9kl8940smk
info:
  title: API to Transliterate API for Resident Services
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /transliteration/transliterate:
    parameters: []
    post:
      summary: Transliterate
      operationId: post-transliteration-transliterate
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  version:
                    type: string
                  responsetime:
                    type: string
                  response:
                    type: object
                    properties:
                      from_field_value:
                        type: string
                      from_field_lang:
                        type: string
                      to_field_value:
                        type: string
                      to_field_lang:
                        type: string
                  errors:
                    type: 'null'
                x-examples:
                  Example 1:
                    id: mosip.resident.transliteration.transliterate
                    version: '1.0'
                    responsetime: '2022-09-07T14:02:41.227Z'
                    response:
                      from_field_value: j
                      from_field_lang: eng
                      to_field_value: ज्
                      to_field_lang: hin
                    errors: null
              examples:
                Success:
                  value:
                    id: mosip.resident.transliteration.transliterate
                    version: '1.0'
                    responsetime: '2022-09-07T14:02:41.227Z'
                    response:
                      from_field_value: j
                      from_field_lang: eng
                      to_field_value: ज्
                      to_field_lang: hin
                    errors: null
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: 'null'
                  version:
                    type: 'null'
                  responsetime:
                    type: string
                  metadata:
                    type: 'null'
                  response:
                    type: 'null'
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        errorCode:
                          type: string
                        message:
                          type: string
                x-examples:
                  Example 1:
                    id: null
                    version: null
                    responsetime: '2022-10-07T09:22:03.631Z'
                    metadata: null
                    response: null
                    errors:
                      - errorCode: KER-ATH-401
                        message: Authentication Failed
              examples:
                Example 1:
                  value:
                    id: null
                    version: null
                    responsetime: '2022-10-07T09:22:03.631Z'
                    metadata: null
                    response: null
                    errors:
                      - errorCode: KER-ATH-401
                        message: Authentication Failed
      description: API to transliterate text from one language to another.
      parameters:
        - schema:
            type: string
          in: cookie
          name: Authorization
          description: Authorization token is used to validate the permissions carried by the user.
          required: true
        - schema:
            type: string
          in: cookie
          name: id_token
          description: ID token is used to verify which user has logged in.
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                request:
                  type: object
                  properties:
                    'from_field_lang ':
                      type: string
                    from_field_value:
                      type: string
                    to_field_lang:
                      type: string
                version:
                  type: string
                requesttime:
                  type: string
              x-examples:
                Example 1:
                  id: mosip.resident.transliteration.transliterate
                  request:
                    'from_field_lang ': 'eng '
                    from_field_value: j
                    to_field_lang: hin
                  version: '1.0'
                  requesttime: '2022-09-07T04:53:07.882Z'
            examples:
              Example 1:
                value:
                  id: mosip.resident.transliteration.transliterate
                  request:
                    'from_field_lang ': 'eng '
                    from_field_value: j
                    to_field_lang: hin
                  version: '1.0'
                  requesttime: '2022-09-07T04:53:07.882Z'
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
