openapi: 3.1.0
x-stoplight:
  id: l42qp4trtkscz
info:
  title: unlock request
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /req​/auth-type-status:
    post:
      summary: /req​/auth-type-status
      operationId: post-req-auth-type-status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: 'null'
                  version:
                    type: 'null'
                  responsetime:
                    type: string
                  metadata:
                    type: 'null'
                  response:
                    type: object
                    properties:
                      status:
                        type: 'null'
                      message:
                        type: string
                  errors:
                    type: 'null'
                x-examples:
                  example-1:
                    id: null
                    version: null
                    responsetime: '2022-06-14T06:10:11.213Z'
                    metadata: null
                    response:
                      status: null
                      message: Notification has been sent to the provided contact detail(s)
                    errors: null
              examples:
                success:
                  value:
                    id: null
                    version: null
                    responsetime: string
                    metadata: null
                    response:
                      status: null
                      message: string
                    errors: null
                Lock authentication types:
                  value:
                    id: mosip.resident.authlock
                    version: v1
                    requesttime: '2022-05-07T08:26:17.944Z'
                    request:
                      individualId: '8251649601'
                      authType:
                        - authType: demo
                          locked: true
                          unlockForSeconds: null
                Unlock authentication types:
                  value:
                    id: mosip.resident.authlock
                    version: v1
                    requesttime: '2022-05-07T08:26:17.944Z'
                    request:
                      individualId: '8251649601'
                      authType:
                        - authType: otp-email
                          locked: false
                          unlockForSeconds: null
                Unlock for authentication types (seconds):
                  value:
                    id: mosip.resident.authlock
                    version: v1
                    requesttime: '2022-05-07T08:26:17.944Z'
                    request:
                      individualId: '8251649601'
                      authType:
                        - authType: otp-email
                          locked: false
                          unlockForSeconds: 600
                Lock/Unlock for authentication types with or without unlockForSeconds in same request:
                  value:
                    id: mosip.resident.authlock
                    version: v1
                    requesttime: '2022-05-07T08:26:17.944Z'
                    request:
                      individualId: '8251649601'
                      authType:
                        - authType: demo
                          locked: true
                          unlockForSeconds: null
                        - authType: otp-email
                          locked: false
                          unlockForSeconds: 600
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                version:
                  type: string
                requesttime:
                  type: string
                request:
                  type: object
                  properties:
                    individualId:
                      type: string
                    authType:
                      type: array
                      items:
                        type: object
                        properties:
                          authType:
                            type: string
                          locked:
                            type: boolean
                          unlockForSeconds:
                            type: integer
              x-examples:
                example-1:
                  id: mosip.resident.authlock
                  version: v1
                  requesttime: '2022-05-07T08:26:17.944Z'
                  request:
                    individualId: '8251649601'
                    authType:
                      - authType: demo
                        locked: false
                        unlockForSeconds: 1
      description: This API is to store the Auth type lock/unlock status with status_comment containing summary of what is locked /unlocked having one entry for each online verification partners with ID as 'request ID + Online verification partner ID'.  Status should be NEW.
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
