openapi: 3.1.0
x-stoplight:
  id: 090mp3cmd71pq
info:
  title: API to Validate Token in the openidconnect login service.
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /authorize​/admin​/validateToken:
    get:
      summary: authorize​/admin​/validateToken
      tags: []
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      operationId: get-authorize-admin-validateToken
      parameters:
        - schema:
            type: string
          in: cookie
          name: Authorization Token
          required: true
      description: 'In the UI, whenever a page requires a login, an API is required to validate the access token, which will be used by the UI. This API is used to verify whether the token is present or not and if it is the correct token or not.'
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
