openapi: 3.1.0
x-stoplight:
  id: bqr3fqeb3q897
info:
  title: API to get document details based on applicant Id
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/proxy​/masterdata​/applicanttype​/{applicantId}​/languages':
    parameters:
      - schema:
          type: string
        name: applicantId
        in: path
        required: true
    get:
      summary: 'proxy​/masterdata​/applicanttype​/{applicantId}​/languages'
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: 'null'
                  version:
                    type: 'null'
                  responsetime:
                    type: string
                  metadata:
                    type: 'null'
                  response:
                    type: object
                    properties:
                      appTypeCode:
                        type: string
                      langCode:
                        type: string
                      isActive:
                        type: boolean
                      documentCategories:
                        type: array
                        items:
                          type: object
                          properties:
                            code:
                              type: string
                            name:
                              type: string
                            description:
                              type: string
                            langCode:
                              type: string
                            isActive:
                              type: boolean
                            documentTypes:
                              type: array
                              items:
                                type: object
                                properties:
                                  code:
                                    type: string
                                  name:
                                    type: string
                                  description:
                                    type: string
                                  langCode:
                                    type: string
                                  isActive:
                                    type: boolean
                  errors:
                    type: 'null'
                x-examples:
                  example-1:
                    id: null
                    version: null
                    responsetime: '2022-06-14T07:51:45.748Z'
                    metadata: null
                    response:
                      appTypeCode: '002'
                      langCode: eng
                      isActive: true
                      documentCategories:
                        - code: POI
                          name: إثبات هوية
                          description: إثبات الهوية
                          langCode: ara
                          isActive: true
                          documentTypes:
                            - code: CIN
                              name: بطاقة الهوية المرجعية
                              description: بطاقة الهوية المرجعية
                              langCode: ara
                              isActive: true
                        - code: POI
                          name: Proof of Identity
                          description: Identity Proof
                          langCode: eng
                          isActive: true
                          documentTypes:
                            - code: CIN
                              name: Reference Identity Card
                              description: Reference Identity Card
                              langCode: eng
                              isActive: true
                        - code: POA
                          name: Un justificatif de domicile
                          description: Preuve dadresse
                          langCode: fra
                          isActive: true
                          documentTypes:
                            - code: RNC
                              name: Contrat de location
                              description: Contrat de location dadresse
                              langCode: fra
                              isActive: true
                        - code: POA
                          name: إثبات العنوان
                          description: إثبات العنوان
                          langCode: ara
                          isActive: true
                          documentTypes:
                            - code: RNC
                              name: عقد ايجار
                              description: اتفاقية تأجير العنوان
                              langCode: ara
                              isActive: true
                        - code: POA
                          name: Proof of Address
                          description: Address Proof
                          langCode: eng
                          isActive: true
                          documentTypes:
                            - code: RNC
                              name: Rental contract
                              description: Rental Agreement of address
                              langCode: eng
                              isActive: true
                        - code: POI
                          name: Preuve didentité
                          description: Preuve didentité
                          langCode: fra
                          isActive: true
                          documentTypes:
                            - code: CIN
                              name: Carte d'identité de référence
                              description: Carte d'identité de référence
                              langCode: fra
                              isActive: true
                    errors: null
              examples:
                Success:
                  value:
                    id: null
                    version: null
                    responsetime: string
                    metadata: null
                    response:
                      appTypeCode: string
                      langCode: string
                      isActive: true
                      documentCategories:
                        - code: string
                          name: string
                          description: string
                          langCode: string
                          isActive: true
                          documentTypes:
                            - code: string
                              name: string
                              description: string
                              langCode: string
                              isActive: true
                    errors: null
      operationId: get-proxy-masterdata-applicanttype-applicantId-languages
      description: This API is to get the details of the uploaded document based on applicant Id.
      parameters:
        - schema:
            type: string
          in: header
          name: applicantId
          required: true
        - schema:
            type: string
          in: header
          name: languages
          required: true
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
