openapi: 3.1.0
x-stoplight:
  id: 8rqp3mryp6j33
info:
  title: unlock status
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /auth-lock-status:
    get:
      summary: /auth-lock-status
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: 'null'
                  version:
                    type: 'null'
                  responsetime:
                    type: string
                  metadata:
                    type: 'null'
                  response:
                    type: object
                    properties:
                      authTypes:
                        type: array
                        items:
                          type: object
                          properties:
                            authType:
                              type: string
                            authSubType:
                              type:
                                - 'null'
                                - string
                            locked:
                              type: boolean
                            unlockForSeconds:
                              type: 'null'
                            requestId:
                              type: 'null'
                            metadata:
                              type: 'null'
                  errors:
                    type: array
                    items:
                      type: object
                      properties: {}
                x-examples:
                  example-1:
                    id: null
                    version: null
                    responsetime: '2022-09-30T04:37:00.466Z'
                    metadata: null
                    response:
                      authTypes:
                        - authType: otp
                          authSubType: email
                          locked: false
                          unlockForSeconds: null
                          requestId: null
                          metadata: null
                        - authType: bio
                          authSubType: FACE
                          locked: false
                          unlockForSeconds: null
                          requestId: null
                          metadata: null
                        - authType: bio
                          authSubType: FINGER
                          locked: false
                          unlockForSeconds: null
                          requestId: null
                          metadata: null
                        - authType: demo
                          authSubType: null
                          locked: true
                          unlockForSeconds: null
                          requestId: null
                          metadata: null
                        - authType: otp
                          authSubType: phone
                          locked: false
                          unlockForSeconds: null
                          requestId: null
                          metadata: null
                        - authType: bio
                          authSubType: IRIS
                          locked: false
                          unlockForSeconds: null
                          requestId: null
                          metadata: null
                    errors: []
              examples:
                Success:
                  value:
                    id: mosip.resident.auth.lock.status
                    version: '1.0'
                    responsetime: '2022-06-15T02:51:50.278Z'
                    response:
                      authTypes:
                        - authType: bio
                          authSubType: FACE
                          locked: false
                          unlockForSeconds: 30
                        - authType: bio
                          authSubType: FINGER
                          locked: false
                          unlockForSeconds: 45
                        - authType: bio
                          authSubType: IRIS
                          locked: false
                          unlockForSeconds: null
                        - authType: demo
                          authSubType: null
                          locked: true
                          unlockForSeconds: null
                        - authType: otp
                          authSubType: email
                          locked: false
                          unlockForSeconds: null
                        - authType: otp
                          authSubType: phone
                          locked: false
                          unlockForSeconds: 50
                    errors: []
                'Error: Unable to access the dependent APIs':
                  value:
                    id: mosip.resident.auth.lock.status
                    version: '1.0'
                    responsetime: '2022-07-22T15:27:10.605Z'
                    response: null
                    errors:
                      errorCode: RES-SER-412
                      message: Unable to access API resource
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: 'null'
                  version:
                    type: 'null'
                  responsetime:
                    type: string
                  metadata:
                    type: 'null'
                  response:
                    type: 'null'
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        errorCode:
                          type: string
                        message:
                          type: string
                x-examples:
                  Example 1:
                    id: null
                    version: null
                    responsetime: '2022-10-07T09:22:03.631Z'
                    metadata: null
                    response: null
                    errors:
                      - errorCode: KER-ATH-401
                        message: Authentication Failed
              examples:
                'Error: Authentication Failure':
                  value:
                    id: null
                    version: null
                    responsetime: '2022-10-07T09:22:03.631Z'
                    metadata: null
                    response: null
                    errors:
                      - errorCode: KER-ATH-401
                        message: Authentication Failed
      operationId: get-auth-lock-status
      parameters:
        - schema:
            type: string
          in: cookie
          name: Authorization
          required: true
          description: Authorization token is used to validate the permissions carried by the user.
        - schema:
            type: string
          in: cookie
          name: id_token
          description: Id token is used to verify which user has logged in.
          required: true
      description: This API is to get the status of various authentication types.
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
