openapi: 3.1.0
x-stoplight:
  id: 7h1cgbx9i00i4
info:
  title: API to Update last date-time when user clicked on the bell notification
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /bell/updatedttime:
    put:
      summary: /bell/updatedttime
      operationId: put-bell-updatedttime
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      parameters:
        - schema:
            type: string
          in: cookie
          name: Authorization Token
          required: true
          description: Authorization token is used to validate the permissions carried by the user.
        - schema:
            type: string
          in: cookie
          name: id_token
          description: ID token is used to verify which user has logged in.
          required: true
      description: |-
        API to update last date-time when user clicked on the bell notification.
        This is an authenticated API. This will update the last date time with current UTC time.
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
