openapi: 3.1.0
x-stoplight:
  id: s3tmdl6sco7mi
info:
  title: API to convert the List of supporting documents request as a downloadable PDF
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/download/supporting-documents?langcode={language-code}':
    parameters:
      - schema:
          type: string
        name: language-code
        in: path
        required: true
    get:
      summary: '/download/supporting-documents?langcode={language-code}'
      tags: []
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: object
                properties: {}
              examples:
                Success:
                  value:
                    Byte array of PDF | mime-type: application/pdf
                example-1:
                  value: {}
            text/html:
              schema:
                type: object
                properties: {}
            application/json:
              schema:
                type: object
                properties: {}
        '':
          description: OK - Supporting doument PDF bytes
          content:
            application/pdf:
              schema:
                type: object
                properties: {}
      operationId: get-pdf-supporting-documents?langCode=-language-code
      parameters:
        - schema:
            type: string
          in: query
          name: langCode
          required: true
          description: 3 letter language code in which the supporting document needs to be returned
      description: This API is to convert the List of supporting documents request as a downloadable PDF
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
