openapi: 3.1.0
x-stoplight:
  id: rfxafsd9blcw2
info:
  title: 'API to track-my-status '
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/events/{event-id}/language/{languageCode}':
    parameters:
      - schema:
          type: string
        name: event-id
        in: path
        required: true
      - schema:
          type: string
        name: languageCode
        in: path
        required: true
    get:
      summary: '/events/{event-id}/language/{languageCode}'
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    id: mosip.resident.event.status
                    version: '1.0'
                    responsetime: '2022-09-08T09:59:03.119Z'
                    metadata: null
                    response:
                      eventId: 86c2ad43-e2a4-4952-bafc-d97ad1e5e453
                      eventType: AUTHENTICATION_REQUEST
                      eventStatus: IN_PROGRESS
                      individualId: '8736474831'
                      summary: AUTHENTICATION_REQUEST
                      timestamp: '2022-07-22T07:05:35.646Z'
                      info:
                        description: 'demo, otp-email, bio-FACE'
                        partnerName: partnerName
                        partnerId: string
                        partnerLogo: Base64encoded image that can be rendered in html
                        authenticationMode: otp
                        vid: vid
                        vidType: vidType
                        downloadCardLink: downloadCardLink
                        orderTrackingLink: orderTrackingLink
                        paymentStatus: failed / success / in-progress
                        partnerTransactionId: string
                        deliveryAddress: string
                        trackingId: trackingId
                    errors: []
                properties:
                  id:
                    type: string
                  version:
                    type: string
                  responsetime:
                    type: string
                  response:
                    type:
                      - object
                      - 'null'
                    properties:
                      eventId:
                        type: string
                      eventType:
                        type: string
                      eventStatus:
                        type: string
                      individualId:
                        type: string
                      summary:
                        type: string
                      timestamp:
                        type: string
                      info:
                        type: object
                        properties:
                          description:
                            type: string
                          partnerName:
                            type: string
                          partnerId:
                            type: string
                          partnerLogo:
                            type: string
                          authenticationMode:
                            type: string
                          vid:
                            type: string
                          vidType:
                            type: string
                          downloadCardLink:
                            type: string
                          orderTrackingLink:
                            type: string
                          paymentStatus:
                            type: string
                          partnerTransactionId:
                            type: string
                          deliveryAddress:
                            type: string
                          trackingId:
                            type: string
                  errors:
                    type:
                      - array
                      - 'null'
                    items:
                      type:
                        - array
                        - object
              examples:
                'Success: Response body structure with All attributes':
                  value:
                    id: mosip.resident.event.status
                    version: '1.0'
                    responsetime: '2022-09-08T09:59:03.119Z'
                    response:
                      eventId: 86c2ad43-e2a4-4952-bafc-d97ad1e5e453
                      eventType: AUTHENTICATION_REQUEST/GENERATE_VID/REVOKE_VID/AUTH_TYPE_LOCK_UNLOCK/UPDATE_MY_UIN/DOWNLOAD_PERSONALIZED_CARD/ORDER_PHYSICAL_CARD/SHARE_CRED_WITH_PARTNER/GET_MY_ID/VERIFY_PHONE_EMAIL
                      eventStatus: IN_PROGRESS
                      individualId: '8736474831'
                      summary: 'Authentication request using demograpihcs, E-Mail OTP, bio-Face Succeeded'
                      timestamp: '2022-07-22T07:05:35.646Z'
                      info:
                        description: 'demo, otp-email, bio-FACE'
                        partnerName: partnerName
                        partnerId: string
                        partnerLogo: Base64encoded image that can be rendered in html
                        authenticationMode: otp
                        vid: vid
                        vidType: vidType
                        downloadCardLink: downloadCardLink
                        orderTrackingLink: orderTrackingLink
                        paymentStatus: failed / success / in-progress
                        partnerTransactionId: string
                        deliveryAddress: string
                        trackingId: trackingId
                    errors: []
                'Error: Invalid Event ID':
                  value:
                    id: mosip.resident.event.status
                    version: '1.0'
                    responsetime: '2022-11-08T06:49:13.830Z'
                    response: null
                    errors:
                      - errorCode: RES-SER-459
                        message: EID not available in database
                'Error: Invalid language code':
                  value:
                    id: mosip.resident.event.status
                    version: '1.0'
                    responsetime: '2022-11-08T06:49:13.830Z'
                    response: null
                    errors:
                      - errorCode: RES-SER-410
                        message: Invalid Input Parameter- languageCode
            application/xml:
              schema:
                type: object
                properties: {}
            multipart/form-data:
              schema:
                type: object
                properties: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Example 1:
                  value:
                    id: null
                    version: null
                    responsetime: '2022-10-07T09:22:03.631Z'
                    metadata: null
                    response: null
                    errors:
                      - errorCode: KER-ATH-401
                        message: Authentication Failed
      operationId: get-events-event-id-language-languageCode
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      parameters:
        - schema:
            type: string
          in: cookie
          name: Authorization
          required: true
          description: Authorization token is used to validate the permissions carried by the user.
        - schema:
            type: string
          in: cookie
          name: id_token
          description: ID token is used to verify which user has logged in.
          required: true
      description: This API is to get the Event Status for the given event-id and language-code.
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
