openapi: 3.1.0
x-stoplight:
  id: 3z78qxght4htl
info:
  title: API to get the immediate children in hierarchy of location
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/proxy​/masterdata​/locations​/immediatechildren​/{locationcode}​':
    parameters:
      - schema:
          type: string
        name: locationcode
        in: path
        required: true
      - schema:
          type: string
        name: langcode
        in: path
        required: true
    get:
      summary: '/proxy​/masterdata​/locations​/immediatechildren​/{locationcode}​/{langcode}'
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: 'null'
                  version:
                    type: 'null'
                  responsetime:
                    type: string
                  metadata:
                    type: 'null'
                  response:
                    type: object
                    properties:
                      locations:
                        type: array
                        items:
                          type: object
                          properties:
                            code:
                              type: string
                            name:
                              type: string
                            hierarchyLevel:
                              type: integer
                            hierarchyName:
                              type: string
                            parentLocCode:
                              type: string
                            langCode:
                              type: string
                            isActive:
                              type: boolean
                  errors:
                    type: 'null'
                x-examples:
                  example-1:
                    id: null
                    version: null
                    responsetime: '2022-06-14T07:41:42.091Z'
                    metadata: null
                    response:
                      locations:
                        - code: RSK
                          name: Rabat Sale Kenitra
                          hierarchyLevel: 1
                          hierarchyName: Region
                          parentLocCode: MOR
                          langCode: eng
                          isActive: true
                    errors: null
              examples:
                Success:
                  value:
                    id: null
                    version: null
                    responsetime: string
                    metadata: null
                    response:
                      locations:
                        - code: string
                          name: string
                          hierarchyLevel: 0
                          hierarchyName: string
                          parentLocCode: string
                          langCode: string
                          isActive: true
                    errors: null
      operationId: get-proxy-masterdata-locations-immediatechildren-locationcode-langcode
      description: This API is to get the immediate children for a location.
      parameters:
        - schema:
            type: string
          in: header
          name: locationcode
          required: true
        - schema:
            type: string
          in: header
          name: langcode
          required: true
      x-stoplight:
        id: lfpdy3vdkuoop
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
