openapi: 3.1.0
x-stoplight:
  id: xf5nirj5wnfhe
info:
  title: API to get details of registration center
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/proxy​/masterdata​/registrationcenters​/page​/{langcode}​/{hierarchylevel}​/{name}':
    parameters:
      - schema:
          type: string
        name: langcode
        in: path
        required: true
      - schema:
          type: string
        name: hierarchylevel
        in: path
        required: true
      - schema:
          type: string
        name: name
        in: path
        required: true
    get:
      summary: '/proxy​/masterdata​/registrationcenters​/page​/{langcode}​/{hierarchylevel}​/{name}'
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: 'null'
                  version:
                    type: 'null'
                  responsetime:
                    type: string
                  metadata:
                    type: 'null'
                  response:
                    type: object
                    properties:
                      pageNo:
                        type: integer
                      pageSize:
                        type: integer
                      sort:
                        type: 'null'
                      totalItems:
                        type: integer
                      totalPages:
                        type: integer
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            isActive:
                              type: boolean
                            createdBy:
                              type: string
                            createdDateTime:
                              type: string
                            updatedBy:
                              type: 'null'
                            updatedDateTime:
                              type: 'null'
                            isDeleted:
                              type: boolean
                            deletedDateTime:
                              type: 'null'
                            id:
                              type: string
                            name:
                              type: string
                            centerTypeCode:
                              type: string
                            addressLine1:
                              type: string
                            addressLine2:
                              type: string
                            addressLine3:
                              type: string
                            latitude:
                              type: string
                            longitude:
                              type: string
                            locationCode:
                              type: string
                            holidayLocationCode:
                              type: string
                            contactPhone:
                              type: string
                            workingHours:
                              type: string
                            langCode:
                              type: string
                            numberOfKiosks:
                              type: integer
                            perKioskProcessTime:
                              type: string
                            centerStartTime:
                              type: string
                            centerEndTime:
                              type: string
                            timeZone:
                              type: string
                            contactPerson:
                              type: string
                            lunchStartTime:
                              type: string
                            lunchEndTime:
                              type: string
                            zoneCode:
                              type: string
                            workingNonWorkingDays:
                              type: 'null'
                            exceptionalHolidayPutPostDto:
                              type: 'null'
                  errors:
                    type: 'null'
                x-examples:
                  example-1:
                    id: null
                    version: null
                    responsetime: '2022-06-14T07:59:55.443Z'
                    metadata: null
                    response:
                      pageNo: 0
                      pageSize: 10
                      sort: null
                      totalItems: 1
                      totalPages: 1
                      data:
                        - isActive: true
                          createdBy: sysadmin
                          createdDateTime: '2022-03-16T08:09:43.412Z'
                          updatedBy: null
                          updatedDateTime: null
                          isDeleted: false
                          deletedDateTime: null
                          id: '10005'
                          name: Center Mehdia
                          centerTypeCode: REG
                          addressLine1: Mehdia Road Amria mehdia
                          addressLine2: Kenitra
                          addressLine3: Maroc
                          latitude: '34.256414'
                          longitude: '-6.675499'
                          locationCode: '14110'
                          holidayLocationCode: KTA
                          contactPhone: '887311749'
                          workingHours: '8:00:00'
                          langCode: eng
                          numberOfKiosks: 1
                          perKioskProcessTime: '00:15:00'
                          centerStartTime: '09:00:00'
                          centerEndTime: '17:00:00'
                          timeZone: '(GTM+01:00) CENTRAL EUROPEAN TIME'
                          contactPerson: Walter Melon
                          lunchStartTime: '13:00:00'
                          lunchEndTime: '14:00:00'
                          zoneCode: BSN
                          workingNonWorkingDays: null
                          exceptionalHolidayPutPostDto: null
                    errors: null
              examples:
                Success:
                  value:
                    id: null
                    version: null
                    responsetime: string
                    metadata: null
                    response:
                      pageNo: 0
                      pageSize: 0
                      sort: null
                      totalItems: 0
                      totalPages: 0
                      data:
                        - isActive: true
                          createdBy: string
                          createdDateTime: string
                          updatedBy: null
                          updatedDateTime: null
                          isDeleted: true
                          deletedDateTime: null
                          id: string
                          name: string
                          centerTypeCode: string
                          addressLine1: string
                          addressLine2: string
                          addressLine3: string
                          latitude: string
                          longitude: string
                          locationCode: string
                          holidayLocationCode: string
                          contactPhone: string
                          workingHours: string
                          langCode: string
                          numberOfKiosks: 0
                          perKioskProcessTime: string
                          centerStartTime: string
                          centerEndTime: string
                          timeZone: string
                          contactPerson: string
                          lunchStartTime: string
                          lunchEndTime: string
                          zoneCode: string
                          workingNonWorkingDays: null
                          exceptionalHolidayPutPostDto: null
                    errors: null
      operationId: get-proxy-masterdata-registrationcenters-page-langcode-hierarchylevel-name
      parameters:
        - schema:
            type: string
          in: header
          name: langcode
          required: true
        - schema:
            type: integer
          in: header
          name: hierarchylevel
          required: true
        - schema:
            type: string
          in: header
          name: name
          required: true
        - schema:
            type: integer
            default: 0
          in: query
          name: pageNumber
        - schema:
            type: integer
            default: 10
          in: query
          name: pageSize
        - schema:
            type: string
            default: createdDateTime
          in: query
          name: sortBy
        - schema:
            type: string
            default: desc
          in: query
          name: orderBy
      description: This API is to get the details about a registration center.
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
