openapi: 3.1.0
x-stoplight:
  id: 4nwkph04k4jyf
info:
  title: UIN
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /download-card:
    post:
      summary: download-card
      operationId: post-download-card
      responses:
        '200':
          description: OK
          content:
            application/pdf:
              schema:
                type: object
                properties: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Example 1:
                  value: {}
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  id: mosip.resident.download.uin.card
                  version: '1.0'
                  requesttime: '2022-04-28T14:14:34.300Z'
                  request:
                    transactionId: '1234567890'
                    individualId: '27847492179376320221124032336'
                    otp: '111111'
              properties:
                id:
                  type: string
                version:
                  type: string
                requesttime:
                  type: string
                request:
                  type:
                    - object
                    - 'null'
                  properties:
                    transactionId:
                      type: string
                    individualId:
                      type: string
                    otp:
                      type: string
            examples:
              Example 1:
                value:
                  id: mosip.resident.download.uin.card
                  version: '1.0'
                  requesttime: '2022-04-28T14:14:34.300Z'
                  request:
                    transactionId: '1234567890'
                    individualId: '27847492179376320221124032336'
                    otp: '111111'
          application/xml:
            schema:
              type: object
              properties: {}
          multipart/form-data:
            schema:
              type: object
              properties: {}
          text/html:
            schema:
              type: object
              properties: {}
          text/plain:
            schema:
              type: object
              properties: {}
          application/EDI-X12:
            schema:
              type: object
              properties: {}
          application/EDIFACT:
            schema:
              type: object
              properties: {}
          application/atom+xml:
            schema:
              type: object
              properties: {}
          application/font-woff:
            schema:
              type: object
              properties: {}
          application/gzip:
            schema:
              type: object
              properties: {}
          application/javascript:
            schema:
              type: object
              properties:
                id:
                  type: string
                version:
                  type: string
                requesttime:
                  type: string
                request:
                  type: object
                  properties:
                    transactionId:
                      type: string
                    individualId:
                      type: string
                    otp:
                      type: string
              x-examples:
                example-1:
                  id: mosip.resident.download.uin.card
                  version: '1.0'
                  requesttime: '2022-04-28T14:14:34.300Z'
                  request:
                    transactionId: '1234567890'
                    individualId: '8251649601'
                    otp: '111111'
            examples:
              example-1:
                value:
                  id: mosip.resident.download.uin.card
                  version: '1.0'
                  requesttime: '2022-04-28T14:14:34.300Z'
                  request:
                    transactionId: '1234567890'
                    individualId: '8251649601'
                    otp: '111111'
      description: This API is to download the UIN card using AID/VID/UIN.
      parameters:
        - schema:
            type: string
          in: cookie
          name: Authentication
          required: true
          description: Authorization token is used to validate the permissions carried by the user.
        - schema:
            type: string
          in: cookie
          name: id_token
          description: ID token is used to verify which user has logged in.
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
