openapi: 3.0.1
info:
  title: AuthTransactionCallback API
  description: API for handling authentication transaction callbacks
  version: 1.0.0
paths:
  callback/credentialStatusUpdate:
    post:
      summary: AuthTransactionCallbackController
      description: AuthTransactionCallbackController
      tags:
        - AuthTransactionCallbackController
      operationId: authTransactionCallback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: OK
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
                example: ''
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
                example: ''
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: string
                example: ''
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: string
                example: ''
      x-stoplight:
        id: krlbq8x2b213w
components:
  securitySchemes:
    PreAuthenticateContentAndVerifyIntent:
      type: apiKey
      in: header
      name: X-Auth-Intent-Secret
      description: secret
security:
  - PreAuthenticateContentAndVerifyIntent: []
