openapi: 3.1.0
x-stoplight:
  id: 8qsxmftxeedmp
info:
  title: Proxy API to get the VID Policy JSON
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /vid​/policy:
    get:
      summary: vid​/policy
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: 'null'
                  version:
                    type: 'null'
                  responsetime:
                    type: 'null'
                  response:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties: {}
                x-examples:
                  example-1:
                    id: null
                    version: null
                    responsetime: null
                    response: '{"vidPolicies":[{"vidType":"Perpetual","vidPolicy":{"validForInMinutes":null,"transactionsAllowed":null,"instancesAllowed":1,"autoRestoreAllowed":true,"restoreOnAction":"REVOKED"}},{"vidType":"Temporary","vidPolicy":{"validForInMinutes":30,"transactionsAllowed":1,"instancesAllowed":5,"autoRestoreAllowed":false,"restoreOnAction":"REGENERATE"}},{"vidType":"OneTimeUse","vidPolicy":{"validForInMinutes":null,"transactionsAllowed":1,"instancesAllowed":1,"autoRestoreAllowed":true,"restoreOnAction":"REVOKED"}}]}'
                    errors: []
              examples:
                Success:
                  value:
                    id: mosip.resident.vid.policy
                    version: '1.0'
                    responsetime: '2022-11-08T06:49:13.830Z'
                    response: '{"vidPolicies":[{"vidType":"Perpetual","vidPolicy":{"validForInMinutes":null,"transactionsAllowed":null,"instancesAllowed":1,"autoRestoreAllowed":true,"restoreOnAction":"REVOKED"}},{"vidType":"Temporary","vidPolicy":{"validForInMinutes":30,"transactionsAllowed":1,"instancesAllowed":5,"autoRestoreAllowed":false,"restoreOnAction":"REGENERATE"}},{"vidType":"OneTimeUse","vidPolicy":{"validForInMinutes":null,"transactionsAllowed":1,"instancesAllowed":1,"autoRestoreAllowed":true,"restoreOnAction":"REVOKED"}}]}'
                    errors: []
                Unable to access policy:
                  value:
                    id: mosip.resident.vid.policy
                    version: '1.0'
                    responsetime: '2022-11-08T06:49:13.830Z'
                    response: null
                    errors:
                      - errorCode: RES-SER-412
                        message: Unable to access API resource
        '401':
          description: Unauthorized
      operationId: get-vid-policy
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  version:
                    type: string
                  requesttime:
                    type: string
                  request:
                    type: object
                    properties:
                      transactionID:
                        type: string
                      vidType:
                        type: string
                      individualId:
                        type: string
                      otp:
                        type: string
              x-examples:
                example-1:
                  - id: string
                    version: string
                    requesttime: string
                    request:
                      transactionID: string
                      vidType: string
                      individualId: string
                      otp: string
            examples: {}
      description: |
        This API is to get the VID policy JSON stored in the mosip-config. 
        For example,
        https://github.com/mosip/mosip-config/blob/master/mosip-vid-policy.json
      parameters:
        - schema:
            type: string
          in: cookie
          description: Authorization token is used to validate the permissions carried by the user.
          name: Authorization
          required: true
        - schema:
            type: string
          in: cookie
          name: id_token
          description: ID token is used to verify which user has logged in.
          required: true
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
