openapi: 3.1.0
x-stoplight:
  id: bhlvp26l7nrd9
info:
  title: VID
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /vids:
    get:
      summary: /vids
      tags: []
      responses:
        '200':
          description: Get VIDs
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    id: null
                    version: null
                    responsetime: null
                    response:
                      - vid: '4251852193'
                        maskedVid: 4XXXXX193
                        vidType: ONETIMEUSE
                        expiryTimestamp: '9999-12-31T23:59:59.1'
                        transactionLimit: 1
                        transactionsLeftCount: 1
                        generatedOnTimestamp: '2022-07-22T15:27:10.605Z'
                      - vid: '5251852193'
                        maskedVid: 5XXXXX193
                        vidType: TEMPORARY
                        expiryTimestamp: '2023-07-22T15:27:10.605Z'
                        transactionLimit: 1
                        transactionsLeftCount: 1
                        generatedOnTimestamp: '2022-07-22T15:27:10.605Z'
                      - vid: '3257206750'
                        maskedVid: 3XXXXX750
                        vidType: PERPETUAL
                        expiryTimestamp: '9999-12-31T23:59:59.1'
                        transactionLimit: null
                        transactionsLeftCount: null
                        generatedOnTimestamp: '2022-07-22T15:27:10.605Z'
                    errors: []
                properties:
                  id:
                    type:
                      - string
                      - 'null'
                  version:
                    type:
                      - string
                      - 'null'
                  responsetime:
                    type:
                      - string
                      - 'null'
                  response:
                    type:
                      - array
                      - 'null'
                    items:
                      type: object
                      properties:
                        vid:
                          type: string
                        maskedVid:
                          type: string
                        vidType:
                          type: string
                        expiryTimestamp:
                          type: string
                        transactionLimit:
                          type:
                            - integer
                            - 'null'
                        transactionsLeftCount:
                          type:
                            - integer
                            - 'null'
                        generatedOnTimestamp:
                          type: string
                  errors:
                    type:
                      - array
                      - 'null'
                    items: {}
              examples:
                Success:
                  value:
                    id: mosip.resident.vid.get
                    version: '1.0'
                    responsetime: '2022-11-09T12:34:33.131Z'
                    response:
                      - vid: '4251852193'
                        maskedVid: 4XXXXX193
                        vidType: ONETIMEUSE
                        expiryTimestamp: '9999-12-31T23:59:59.1'
                        transactionLimit: 1
                        transactionsLeftCount: 1
                        generatedOnTimestamp: '2022-07-22T15:27:10.605Z'
                      - vid: '5251852193'
                        maskedVid: 5XXXXX193
                        vidType: TEMPORARY
                        expiryTimestamp: '2023-07-22T15:27:10.605Z'
                        transactionLimit: 1
                        transactionsLeftCount: 1
                        generatedOnTimestamp: '2022-07-22T15:27:10.605Z'
                      - vid: '3257206750'
                        maskedVid: 3XXXXX750
                        vidType: PERPETUAL
                        expiryTimestamp: '9999-12-31T23:59:59.1'
                        transactionLimit: null
                        transactionsLeftCount: null
                        generatedOnTimestamp: '2022-07-22T15:27:10.605Z'
                    errors: []
                Unable to access:
                  value:
                    id: mosip.resident.vid.get
                    version: '1.0'
                    responsetime: '2022-11-08T06:49:13.830Z'
                    response: null
                    errors:
                      - errorCode: RES-SER-412
                        message: Unable to access API resource
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                'Error: Authentication Failure':
                  value:
                    id: null
                    version: null
                    responsetime: '2022-10-07T09:22:03.631Z'
                    response: null
                    errors:
                      - errorCode: KER-ATH-401
                        message: Authentication Failed
      operationId: get-vids
      parameters:
        - schema:
            type: string
          in: cookie
          name: Authorization token
          required: true
          description: Authorization token is used to validate the permissions carried by the user.
        - schema:
            type: string
          in: cookie
          name: id_token
          description: Id token is used to verify which user has logged in.
          required: true
        - schema:
            type: string
          in: header
          name: locale
          description: Locale based on Language and country. Used in date time formatting. Ex. en-US
        - schema:
            type: string
          in: header
          name: time-zone-offset
          description: Used in time conversion per the client on any timestamps returned in the response. Ex. -330 - for India
      description: This is an authenticated API that will retrieve the list of active VIDs of the UIN/VID of the logged in session.
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
