-- -------------------------------------------------------------------------------------------------
-- Database Name: mosip_resident
-- Release Version 	: 1.2.1
-- Purpose    		: Database scripts for Resident Service DB.       
-- Create By   		: Manoj SP
-- Created Date		: April-2022
-- 
-- Modified Date        Modified By         Comments / Remarks
-- --------------------------------------------------------------------------------------------------
-- April-2022			Manoj SP	    drop mosip_resident db scripts added.
-----------------------------------------------------------------------------------------------------
DROP DATABASE IF EXISTS mosip_resident;
-----------------------------------------------------------------------------------------------------