package io.mosip.resident.util;

import static io.mosip.resident.constant.RegistrationConstants.FAILURE;
import static io.mosip.resident.constant.RegistrationConstants.INFO;
import static io.mosip.resident.constant.RegistrationConstants.RESIDENT_APPLICATION_ID;
import static io.mosip.resident.constant.RegistrationConstants.RESIDENT_APPLICATION_NAME;
import static io.mosip.resident.constant.RegistrationConstants.SUCCESS;

public enum AuditEnum implements AuditEvent {

	VALIDATE_REQUEST("RES-SER-110", INFO, "Validating input request", "Validating input request of %s", "RS-VAL_REQ",
			"Validate request", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	OBTAINED_RID("RES-SER-114", SUCCESS, "Request print UIN",
			"Obtained RID for transaction id %s while requesting for printing UIN", "RS-RID", "RID section",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	OBTAINED_RID_UIN_UPDATE("RES-SER-115", SUCCESS, "Request UIN Update",
			"Obtained RID for transaction id %s while requesting for update UIN", "RS-RID", "RID section",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	VID_GENERATED("RES-SER-117", SUCCESS, "Request to generate VID", "VID generated for transaction id %s",
			"RS-VID_GEN", "VID generation", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	CREATE_PACKET("RES-SER-118", INFO, "Request to create packet", "Started packet creation", "RS-PACK",
			"Packet creation", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	PACKET_CREATED("RES-SER-119", SUCCESS, "Request to upload UIN packet", "Uploading UIN packet", "RS-PACK",
			"Packet creation", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	PACKET_SYNC("RES-SER-120", INFO, "Request to upload UIN packet", "Sync packet", "RS-PACK", "Packet creation",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	OTP_GEN_SUCCESS("RES-SER-122", SUCCESS, "generating otp: Success", "otp generation is success", "RS-OTP-GEN",
			"Otp generation", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	OTP_GEN_EXCEPTION("RES-SER-123", FAILURE, "generating otp: Exception", "otp generation is failed", "RS-OTP-GEN",
			"Otp generation", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	CREDENTIAL_REQ_SUCCESS("RES-SER-125", SUCCESS, "Sharing credential to partner: Success",
			"Sharing credential to partner is succeded", "RS-CRED_REQ", "Credential request", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	CREDENTIAL_REQ_EXCEPTION("RES-SER-126", FAILURE, "Sharing credential to partner: Failed",
			"Sharing credential to partner is failed", "RS-CRED_REQ", "Credential request", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	CREDENTIAL_REQ_STATUS_SUCCESS("RES-SER-128", SUCCESS, "credential status: Success",
			"credential req status is success", "RS-CRED_REQ", "Credential request", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	CREDENTIAL_REQ_STATUS_EXCEPTION("RES-SER-129", FAILURE, "credential status: Exception",
			"credential req status is failed", "RS-CRED_REQ", "Credential request", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	CREDENTIAL_CANCEL_REQ_SUCCESS("RES-SER-131", SUCCESS, "credential cancel request: Success",
			"credential cancel request success", "RS-CRED_REQ", "Credential request", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	CREDENTIAL_CANCEL_REQ_EXCEPTION("RES-SER-132", FAILURE, "credential cancel request: Exception",
			"credential cancel request failed", "RS-CRED_REQ", "Credential request", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	CREDENTIAL_TYPES_SUCCESS("RES-SER-134", SUCCESS, "credential types: Success", "fetch credential type success",
			"RS-CRED_TYP", "Credential type", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	CREDENTIAL_TYPES_EXCEPTION("RES-SER-135", FAILURE, "credential types: Exception", "fetch credential types failed",
			"RS-CRED_TYP", "Credential type", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	REQ_CARD_SUCCESS("RES-SER-137", SUCCESS, "request for card: Success", "request for card is success", "RS-CARD",
			"Request card", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	REQ_CARD_EXCEPTION("RES-SER-138", FAILURE, "request for card: Exception", "request for card is failed", "RS-CARD",
			"Request card", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	REQ_POLICY_SUCCESS("RES-SER-140", SUCCESS, "request for policy: Success", "request for policy is success", "RS-POL",
			"Request policy", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	REQ_POLICY_EXCEPTION("RES-SER-141", FAILURE, "request for policy: Exception", "request for policy is failed",
			"RS-POL", "Request policy", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	VALIDATION_FAILED_EXCEPTION("RES-SER-142", FAILURE, "Validation failed", "Validation failed : %s", "RS-VAL",
			"Validation", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_VALID_DOCUMENT_SUCCESS("RES-SER-143", SUCCESS, "get valid documents: Success",
			"get valid documents by lang code is succeed", "RS-DOC", "Document", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_VALID_DOCUMENT_EXCEPTION("RES-SER-144", FAILURE, "get valid documents: Exception",
			"get valid documents by lang code is failed", "RS-DOC", "Document", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_LOCATION_HIERARCHY_LEVEL_SUCCESS("RES-SER-145", SUCCESS, "get location hierarchy levels: Success",
			"get location hierarchy level by lang code is succeed", "RS-LOC", "Location", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_LOCATION_HIERARCHY_LEVEL_EXCEPTION("RES-SER-146", FAILURE, "get location hierarchy levels: Failed",
			"get location hierarchy level by lang code is failed", "RS-LOC", "Location", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_LOCATION_HIERARCHY_LEVEL_ALL_LANG_SUCCESS("RES-SER-147", SUCCESS,
			"get location hierarchy levels for all language: Success", "get location hierarchy level is succeed",
			"RS-LOC", "Location", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_LOCATION_HIERARCHY_LEVEL_ALL_LANG_EXCEPTION("RES-SER-148", FAILURE,
			"get location hierarchy levels for all language: Failed", "get location hierarchy level is failed",
			"RS-LOC", "Location", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_ALL_DYNAMIC_FIELD_VALUE_SUCCESS("RES-SER-149", SUCCESS, "get all dynamic field value: Success",
			"get all dynamic field value is succeed", "RS-DYNAMIC", "Dynamic field", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_ALL_DYNAMIC_FIELD_VALUE_EXCEPTION("RES-SER-150", FAILURE, "get all dynamic field value: Failed",
			"get all dynamic field value is failed", "RS-DYNAMIC", "Dynamic field", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_IMMEDIATE_CHILDREN_SUCCESS("RES-SER-151", SUCCESS, "get immediate children: Success",
			"get immediate children by location code and lang code is succeed", "RS-CHILD", "Immediate children",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_IMMEDIATE_CHILDREN_EXCEPTION("RES-SER-152", FAILURE, "get immediate children: Exception",
			"get immediate children by location code and lang code is failed", "RS-CHILD", "Immediate children",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_LOCATION_DETAILS_SUCCESS("RES-SER-153", SUCCESS, "get location details: Success",
			"get location details by location code and lang code is succeed", "RS-LOC", "Location",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_LOCATION_DETAILS_EXCEPTION("RES-SER-154", FAILURE, "get location details: Exception",
			"get location details by location code and lang code is failed", "RS-LOC", "Location",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_COORDINATE_SPECIFIC_REG_CENTERS_SUCCESS("RES-SER-155", SUCCESS, "get coordinate specific registration centers",
			"get coordinate specific registration centers: Success", "RS-REG", "Registration center",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_COORDINATE_SPECIFIC_REG_CENTERS_EXCEPTION("RES-SER-156", FAILURE,
			"get coordinate specific registration centers", "get coordinate specific registration centers: Failed",
			"RS-REG", "Registration center", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_APPLICANT_VALID_DOCUMENT_SUCCESS("RES-SER-157", SUCCESS, "get applicant valid documents: Success",
			"get applicant valid documents is succeed", "RS-DOC", "Document", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_APPLICANT_VALID_DOCUMENT_EXCEPTION("RES-SER-158", FAILURE, "get applicant valid documents: Exception",
			"get applicant valid documents is failed", "RS-DOC", "Document", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_REG_CENTERS_FOR_LOCATION_CODE_SUCCESS("RES-SER-159", SUCCESS,
			"get registration centers for location code: Success",
			"get registration centers for location code: Success", "RS-REG_LOC", "Registration center location",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_REG_CENTERS_FOR_LOCATION_CODE_EXCEPTION("RES-SER-160", FAILURE,
			"get registration centers for location code: Exception",
			"get registration centers for location code: Failed", "RS-REG_LOC", "Registration center location",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_REG_CENTERS_PAGINATED_SUCCESS("RES-SER-161", SUCCESS, "get registration centers paginated: Success",
			"get registration centers paginated is succeed", "RS-REG", "Registration center", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_REG_CENTERS_PAGINATED_EXCEPTION("RES-SER-162", FAILURE, "get registration centers paginated: Exception",
			"get registration centers paginated: Failed", "RS-REG", "Registration center", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_REG_CENTER_WORKING_DAYS_SUCCESS("RES-SER-163", SUCCESS, "get registration center working days success",
			"get registration center working days: Success", "RS-REG", "Registration center", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_REG_CENTER_WORKING_DAYS_EXCEPTION("RES-SER-164", FAILURE, "get registration center working days failure",
			"get registration center working days: Failed", "RS-REG", "Registration center", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_LATEST_ID_SCHEMA_SUCCESS("RES-SER-165", SUCCESS, "get latest id schema: Success",
			"get latest id schema is succeeded", "RS-ID_SCH", "ID schema", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_LATEST_ID_SCHEMA_EXCEPTION("RES-SER-166", FAILURE, "get latest id schema: Failed",
			"get latest id schema is failed", "RS-ID_SCH", "ID schema", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_TEMPLATES_SUCCESS("RES-SER-167", SUCCESS, "get templates: Success",
			"get templates by langCode and templateTypeCode is succeeded", "RS-TEMP", "Templates section",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_TEMPLATES_EXCEPTION("RES-SER-168", FAILURE, "get templates: Failed",
			"get templates by langCode and templateTypeCode is failed", "RS-TEMP", "Templates section",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_CONFIGURATION_PROPERTIES_SUCCESS("RES-SER-169", SUCCESS, "get resident configuration properties success",
			"get resident configuration properties: Success", "RS-CONF", "Config properties", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_CONFIGURATION_PROPERTIES_EXCEPTION("RES-SER-170", FAILURE, "get resident configuration properties failure",
			"get resident configuration properties: Failed", "RS-CONF", "Config properties", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_DYNAMIC_FIELD_BASED_ON_LANG_CODE_AND_FIELD_NAME_SUCCESS("RES-SER-171", SUCCESS,
			"get dynamic field based on lang code and field name: Success",
			"get dynamic field based on langCode and field name is succeeded", "RS-GEND", "Dynamic Field",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_DYNAMIC_FIELD_BASED_ON_LANG_CODE_AND_FIELD_NAME_EXCEPTION("RES-SER-172", FAILURE,
			"get dynamic field based on lang code and field name: Failed",
			"get dynamic field based on langCode and field name is failed", "RS-GEND", "Dynamic Field",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	UPLOAD_DOCUMENT_SUCCESS("RES-SER-177", SUCCESS, "Document upload: Success",
			"document upload success for transaction id %s", "RS-DOC", "Document", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	UPLOAD_DOCUMENT_FAILED("RES-SER-178", FAILURE, "Document upload: Failed",
			"document upload failed for transaction id %s", "RS-DOC", "Document", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_DOCUMENTS_METADATA_SUCCESS("RES-SER-180", SUCCESS, "Get documents: Success",
			"get documents success for transaction id %s", "RS-DOC", "Document", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_DOCUMENTS_METADATA_FAILED("RES-SER-181", FAILURE, "Get documents: Failed",
			"Get documents failed for transaction id %s", "RS-DOC", "Document", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	REQ_AUTH_LOCK_STATUS_SUCCESS("RES-SER-183", SUCCESS, "Request auth lock status: Success",
			"Requesting auth lock status api is success", "RS-AUTH_LOCK", "Auth lock", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	REQ_AUTH_LOCK_STATUS_FAILED("RES-SER-184", FAILURE, "Request auth lock status: Failed",
			"Requesting auth lock status api is failed", "RS-AUTH_LOCK", "Auth lock", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_PARTNERS_BY_PARTNER_TYPE_SUCCESS("RES-SER-187", SUCCESS, "get partners by partner type: Success",
			"get partners by partner type is succeeded", "RS-PARTN", "Partner section", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_PARTNERS_BY_PARTNER_TYPE_EXCEPTION("RES-SER-188", FAILURE, "get partners by partner type: Failed",
			"get partners by partner type is failed", "RS-PARTN", "Partner section", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_VIDS_SUCCESS("RES-SER-192", SUCCESS, "get vids success", "get vids: Success", "RS-VID", "VID",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_VIDS_EXCEPTION("RES-SER-193", FAILURE, "get vids failure", "get vids: Failed", "RS-VID", "VID",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	OTP_INDIVIDUALID_GEN_SUCCESS("RES-SER-195", SUCCESS, "generating otp for Individual ID: Success",
			"otp generation for Individual ID is success", "RS-OTP_GEN", "Otp generation", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	OTP_AID_GEN_EXCEPTION("RES-SER-196", FAILURE, "generating otp for aid: Failed", "otp generation for aid is failed",
			"RS-OTP_GEN", "Otp generation", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_INPUT_ATTRIBUTES_SUCCESS("RES-SER-198", SUCCESS, "get identity attributes success",
			"get identity attributes: Success", "RS-INP_ATTR", "Input attribute", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_INPUT_ATTRIBUTES_EXCEPTION("RES-SER-199", FAILURE, "get identity attributes failure",
			"get identity attributes: Failed", "RS-INP_ATTR", "Input attribute", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	RID_STATUS_SUCCESS("RES-SER-200", SUCCESS, "RID status: Success", "Request for checking RID status is success",
			"RS-RID", "RID Status", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),

	REQ_PRINTUIN_SUCCESS("RES-SER-201", SUCCESS, "Request print UIN: Success",
			"Requesting print uin api for transaction id %s is success", "RS-UIN", "UIN", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	REQ_AUTH_LOCK_SUCCESS("RES-SER-202", SUCCESS, "Request auth lock: Success",
			"Requesting auth lock api for transaction id %s is success", "RS-AUTH_LOCK_UNLOCK", "Auth lock/unlock",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	REQ_AUTH_UNLOCK_SUCCESS("RES-SER-203", SUCCESS, "Request auth unlock: Success",
			"Requesting auth unlock api for transaction id %s is success", "RS-AUTH_LOCK_UNLOCK", "Auth lock/unlock",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	REQ_AUTH_HISTORY_SUCCESS("RES-SER-204", SUCCESS, "Request auth history: Success",
			"Requesting auth history api for transaction id %s is success", "RS-AUTH_HIST", "Auth history",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	UPDATE_UIN_SUCCESS("RES-SER-205", SUCCESS, "Request update uin: Success",
			"Requesting update uin api for transaction id %s is success", "RS-UIN", "UIN", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GENERATE_VID_SUCCESS("RES-SER-206", SUCCESS, "Request for generating VID: Success",
			"Request for generating VID for transaction id %s is success", "RS-GEN_REV_VID", "Generate/Revoke VID",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),

	GENERATE_VID_SUCCESS_V1("RES-SER-206", SUCCESS, "Request for generating VID: Success",
			"Request for generating VID is success", "RS-GEN_REV_VID", "Generate/Revoke VID",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	REVOKE_VID_SUCCESS("RES-SER-207", SUCCESS, "Request for revoking VID: Success",
			"Request for revoking VID for transaction id %s is success", "RS-GEN_REV_VID", "Generate/Revoke VID",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),

	REVOKE_VID_SUCCESS_V1("RES-SER-207", SUCCESS, "Request for revoking VID: Success",
			"Request for revoking VID is success", "RS-GEN_REV_VID", "Generate/Revoke VID",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	SEND_NOTIFICATION_SUCCESS("RES-SER-208", SUCCESS, "Send notification: Success",
			"Sending notification for transaction id %s", "RS-NOT", "Notification section", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	VALIDATE_OTP_SUCCESS("RES-SER-209", SUCCESS, "Validate otp: Success",
			"Validating OTP for transaction id %s is success", "RS-OTP", "Otp section", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	VALIDATE_OTP_FAILURE("RES-SER-210", FAILURE, "Validate otp: Failed",
			"OTP vaildation for transaction id %s is failed", "RS-OTP", "Otp section", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	AID_STATUS_SUCCESS("RES-SER-211", SUCCESS, "Checking AID status: Success",
			"Request for checking AID status is success", "RS-AID", "AID status", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	AID_STATUS_FAILURE("RES-SER-212", FAILURE, "Checking AID status: Failed", "Request for checking AID status failed",
			"RS-AID", "AID status", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	REQ_AUTH_LOCK_UNLOCK_SUCCESS("RES-SER-213", SUCCESS, "Request auth lock unlock: Success",
			"Requesting auth lock unlock api is success", "RS-AUTH_LOCK_UNLOCK", "Auth lock/unlock",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	REQ_SERVICE_REQUEST_UPDATE("RES-SER-215", SUCCESS, "Request service request update",
			"Requesting service request update is success", "RS-SER_HIS", "Service history", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	REQ_SERVICE_REQUEST_UPDATE_SUCCESS("RES-SER-216", SUCCESS, "Request service request update: Success",
			"Requesting service request update is success", "RS-SER_HIS", "Service history", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	IDA_TOKEN_NOT_FOUND("RES-SER-217", FAILURE, "IDA token not found", "IDA token not found", "RS-IDA_TOK", "IDA token",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	REQ_CUSTOM_CREDENTIAL("RES-SER-218", INFO, "Custom Credential Request", "Custom Credential Request", "RES-CUS_CRED",
			"Custom credential", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	REQ_CUSTOM_CREDENTIAL_SUCCESS("RES-SER-219", SUCCESS, "Custom Credential Request: Success",
			"Custom Credential Request is success", "RES-CUS_CRED", "Custom credential", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	REQ_CUSTOM_CREDENTIAL_FAILURE("RES-SER-220", FAILURE, "Custom Credential Request: Failed",
			"Custom Credential Request has failed", "RES-CUS_CRED", "Custom credential", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	CHANNEL_VERIFICATION_STATUS("RES-SER-221", INFO, "Check Channel Verification status Request",
			"Check Channel Verification status Request", "RS-CHAN_VER", "Channel verification", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	CHANNEL_VERIFICATION_STATUS_SUCCESS("RES-SER-222", SUCCESS, "Check Channel Verification status Request: Success",
			"Check Channel Verification status Request is success", "RS-CHAN_VER", "Channel verification",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	CHANNEL_VERIFICATION_STATUS_FAILURE("RES-SER-223", FAILURE, "Custom Credential Request: Failed",
			"Custom Credential Request has failed", "RS-CHAN_VER", "Channel verification", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_VID_POLICY("RES-SER-224", INFO, "Get VID Policy Request", "Get VID Policy Request", "RS-VID", "VID",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_VID_POLICY_SUCCESS("RES-SER-225", SUCCESS, "Get VID Policy Request: Success",
			"Get VID Policy Request is success", "RS-VID", "VID", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_VID_POLICY_FAILURE("RES-SER-226", FAILURE, "Get VID Policy Request: Failed",
			"Get VID Policy Request has failed", "RS-VID", "VID", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_IDMAPPING("RES-SER-227", INFO, "get identity mapping json", "get identity mapping json", "RS-ID_MAP",
			"ID mapping", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_IDMAPPING_SUCCESS("RES-SER-228", SUCCESS, "get identity mapping json success",
			"get identity mapping json: Success", "RS-ID_MAP", "ID mapping", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_IDMAPPING_EXCEPTION("RES-SER-229", FAILURE, "get identity mapping json failure",
			"get identity mapping json: Failed", "RS-ID_MAP", "ID mapping", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	RID_DIGITAL_CARD_REQ_SUCCESS("RES-SER-231", SUCCESS, "Download digital card request: Success",
			"Download digital card request is succeeded", "RS-RID_CARD", "NO_ID_TYPE", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	RID_DIGITAL_CARD_REQ_FAILURE("RES-SER-232", FAILURE, "Download digital card request: Failed",
			"Download digital card request is failed", "RS-RID_CARD", "RID digital card", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	CHECK_AID_STATUS_REQUEST_SUCCESS("RES-SER-233", SUCCESS, "Request AID status: Success",
			"Requesting AID status for eventId %s is succeeded", "RS-AID", "AID status", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	CHECK_AID_STATUS_REQUEST_FAILED("RES-SER-234", FAILURE, "Request AID status: Failed",
			"Requesting AID status  for eventId %s is failed", "RS-AID", "AID status", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	SEND_PHYSICAL_CARD_SUCCESS("RES-SER-237", SUCCESS, "send a physical card: Success",
			"send a physical card is succeeded", "RS-PHYS_CARD", "Physical card", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	SEND_PHYSICAL_CARD_EXCEPTION("RES-SER-238", FAILURE, "send a physical card: Exception",
			"send a physical card is failed", "RS-PHYS_CARD", "Physical card", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_DOCUMENT_BY_DOC_ID_SUCCESS("RES-SER-240", SUCCESS, "get document by doc id: Success",
			"get document by doc id is succeeded", "RS-DOC", "Document", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_DOCUMENT_BY_DOC_ID_FAILED("RES-SER-241", FAILURE, "get document by doc id: Failed",
			"get document by doc id is failed", "RS-DOC", "Document", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	DELETE_DOCUMENT_SUCCESS("RES-SER-243", SUCCESS, "delete document: Success", "delete document is succeeded",
			"RS-DOC", "Document", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	DELETE_DOCUMENT_FAILED("RES-SER-244", FAILURE, "delete document: Failed", "delete document is failed", "RS-DOC",
			"Document", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_IDENTITY_UPDATE_COUNT_SUCCESS("RES-SER-249", SUCCESS, "get identity update count: Success",
			"retrieve remaining update counts for each id attributes for a UIN/VID is succeeded", "RS-IDEN_COUN",
			"Identity count", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_IDENTITY_UPDATE_COUNT_EXCEPTION("RES-SER-250", FAILURE, "get identity update count: Failed",
			"retrieve remaining update counts for each id attributes for a UIN/VID is failed", "RS-IDEN_COUN",
			"Identity count", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	PIN_STATUS_SUCCESS("RES-SER-251", SUCCESS, "pin status success", "pin status success based on event id: Success",
			"RS-PIN", "Pin status", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	PIN_STATUS_FAILURE("RES-SER-252", FAILURE, "pin status failure", "pin status failure based on event id: Failed",
			"RS-PIN", "Pin status", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	UN_PIN_STATUS_SUCCESS("RES-SER-253", SUCCESS, "un pin status: Success", "un pin status success based on event id",
			"RS-PIN", "Pin status", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	UN_PIN_STATUS_FAILURE("RES-SER-254", FAILURE, "un pin status: Failed", "un pin status failure based on event id",
			"RS-PIN", "Pin statusE", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_ACKNOWLEDGEMENT_DOWNLOAD_URL_SUCCESS("RES-SER-255", SUCCESS, "get acknowledgement download url: Success",
			"get acknowledgement download url is succeeded", "RS-ACK_DOWN", "Acknowledgement download",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_ACKNOWLEDGEMENT_DOWNLOAD_URL_FAILURE("RES-SER-256", FAILURE, "get acknowledgement download url: Failed",
			"get acknowledgement download url failed", "RS-ACK_DOWN", "Acknowledgement download",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	SEND_OTP_SUCCESS("RES-SER-259", SUCCESS, "send otp: Success", "send otp is success for userId: %s", "RS-OTP",
			"Otp section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	SEND_OTP_FAILURE("RES-SER-260", FAILURE, "send otp: Failed", "send otp is failed for userId: %s", "RS-OTP",
			"Otp section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	DOWNLOAD_SERVICE_HISTORY_SUCCESS("RES-SER-265", SUCCESS, "download service history: Success",
			"download service history success based on language code", "RS-DOWN_SER", "Download service history",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	DOWNLOAD_SERVICE_HISTORY_FAILURE("RES-SER-266", FAILURE, "download service history: Failed",
			"download service history failed", "RS-DOWN_SER", "Download service history", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	INVALID_REQUEST_TYPE_CODE("RES-SER-267", FAILURE, "Invalid request type code",
			"Invalid Request Type. Please input eventId only for VID_CARD_DOWNLOAD and UPDATE_MY_UIN",
			"RS-VAL", "Validation", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	DOWNLOAD_REGISTRATION_CENTER_SUCCESS("RES-SER-269", SUCCESS, "download registration center: Success",
			"download registration center success based on language code and hierarchy level", "RS-DOWN_CARD",
			"Download card", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	DOWNLOAD_REGISTRATION_CENTER_FAILURE("RES-SER-270", FAILURE, "Download registration center: Failed",
			"Download registration center is failed", "RS-DOWN_CARD", "Download card", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	DOWNLOAD_SUPPORTING_DOCS_SUCCESS("RES-SER-271", SUCCESS, "Download supporting docs: Success",
			"Download supporting docs success based on language code", "RS-DOWN_CARD", "Download card",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	DOWNLOAD_SUPPORTING_DOCS_FAILURE("RES-SER-272", FAILURE, "Download supporting docs: Failed",
			"Download supporting docs failed", "RS-DOWN_CARD", "Download card", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	DOWNLOAD_REGISTRATION_CENTER_NEAREST_SUCCESS("RES-SER-273", SUCCESS,
			"Download nearest registration center: Success",
			"Download nearest registration center success based on language code,longitude,latitude and distance",
			"RS-DOWN_CARD", "Download card", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	DOWNLOAD_REGISTRATION_CENTER_NEAREST_FAILURE("RES-SER-274", FAILURE, "Download nearest registration center: Failed",
			"Download nearest registration center failed", "RS-DOWN_CARD", "Download card", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_DOCUMENT_TYPES_SUCCESS("RES-SER-275", SUCCESS, "get document types: Success",
			"get document types by documentCode and langCode is succeeded", "RS-DOC", "Document",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_DOCUMENT_TYPES_EXCEPTION("RES-SER-276", FAILURE, "get document types: Failed",
			"get document types by documentCode and langCode is failed", "RS-DOC", "Document", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_GENDER_CODE_SUCCESS("RES-SER-277", SUCCESS, "get gender code: Success",
			"get gender code by genderName and langCode is succeeded", "RS-GEND", "Gender", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_GENDER_CODE_EXCEPTION("RES-SER-278", FAILURE, "get gender code: Failed",
			"get gender code by genderName and langCode is failed", "RS-GEND", "Gender", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GRIEVANCE_TICKET_REQUEST_SUCCESS("RES-SER-279", SUCCESS, "Grievance ticket request: Success",
			"Grievance ticket request success", "RS-GRIEV", "Grievance ticket", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GRIEVANCE_TICKET_REQUEST_FAILED("RES-SER-280", FAILURE, "Grievance ticket request: Failed",
			"Grievance ticket request failed", "RS-GRIEV", "Grievance ticket", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	LOGIN_REQ("RES-SER-281", INFO, "Login Request", "Login Request", "RS-LOGN", "Login req", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	LOGIN_REQ_SUCCESS("RES-SER-282", SUCCESS, "Login Request: Success", "Login request is success", "RS-LOGN",
			"Login req", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	LOGIN_REQ_FAILURE("RES-SER-283", FAILURE, "Login Request: Failed", "Login request is failed", "RS-LOGN",
			"Login req", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	LOGOUT_REQ("RES-SER-284", INFO, "Logout Request", "Logout Request", "RS-LOGN", "Logout req",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	LOGOUT_REQ_SUCCESS("RES-SER-285", SUCCESS, "Logout Request: Success", "Logout request is success", "RS-LOGO",
			"Logout req", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	LOGOUT_REQ_FAILURE("RES-SER-286", FAILURE, "Logout Request: Failed", "Logout request is failed", "RS-LOGO",
			"Logout req", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	VALIDATE_TOKEN_SUCCESS("RES-SER-287", SUCCESS, "Validate Token: Success", "Validate token is success", "RS-VAL",
			"Validate token", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	VALIDATE_TOKEN_FAILURE("RES-SER-288", FAILURE, "Validate Token: Failed", "Validate token is failed", "RS-VAL",
			"Validate token", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	DOWNLOAD_PERSONALIZED_CARD_FAILURE("RES-SER-291", FAILURE, "Download personalized card: Failed",
			"Download card Html to pdf failed", "RS-DOWN_CARD", "Download card", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	DOWNLOAD_PERSONALIZED_CARD_SUCCESS("RES-SER-292", SUCCESS, "Download personalized card: Success",
			"Download card Html to pdf success", "RS-DOWN_CARD", "Download card", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	AID_STAGE_SUCCESS("RES-SER-293", SUCCESS, "Check AID stage status: Success", "Check AID stage status is success",
			"RS-AID_STAGE", "AID stage", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	AID_STAGE_FAILURE("RES-SER-294", FAILURE, "Check AID stage status: Failed", "Check AID stage status is failed",
			"RS-AID_STAGE", "AID stage", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	CREDENTIAL_STATUS_UPDATE_CALL_BACK_SUCCESS("RES-SER-299", SUCCESS, "Credential status update call back: Success",
			"credential status update call back success for transaction id %s", "RS-CRED_STAT_UPD",
			"Credential status update", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	CREDENTIAL_STATUS_UPDATE_CALL_BACK_FAILURE("RES-SER-300", FAILURE, "Credential status update call back: Failed",
			"credential status update call back failure for transaction id %s", "RS-CRED_STAT_UPD",
			"Credential status update", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),

	RID_STATUS_FAILURE("RES-SER-302", FAILURE, "RID status: Failed", "Request for checking RID status failed- %s",
			"RS-RID", "RID Status", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_SERVICE_HISTORY_SUCCESS("RES-SER-303", SUCCESS, "get service history: Success",
			"get service history is success", "RS-SERV_HIS", "Service history", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_SERVICE_HISTORY_FAILURE("RES-SER-304", FAILURE, "get service history: Failed", "get service history failed",
			"RS-SERV_HIS", "Service history", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	UPDATE_UIN_FAILURE("RES-SER-305", FAILURE, "Request update uin: Failed", "Requesting update uin failed", "RS-UIN",
			"UIN", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	UNREAD_NOTIF_COUNT_SUCCESS("RES-SER-306", SUCCESS, "Unread notification count: Success",
			"Unread notification count is success", "RS-NOT", "Notification section", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	UNREAD_NOTIF_COUNT_FAILURE("RES-SER-307", FAILURE, "Unread notification count: Failed",
			"Unread notification count failed", "RS-NOT", "Notification section", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_NOTIFICATION_SUCCESS("RES-SER-309", SUCCESS, "Get notification: Success", "Get notification is Success",
			"RS-NOT", "Notification section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_NOTIFICATION_FAILURE("RES-SER-310", FAILURE, "Get notification: Failed", "Get notification failed", "RS-NOT",
			"Notification section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_NOTIF_CLICK_SUCCESS("RES-SER-311", SUCCESS, "Get notification click: Success",
			"Get notification click is Success", "RS-NOT", "Notification section", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	GET_NOTIF_CLICK_FAILURE("RES-SER-312", FAILURE, "Get notification click: Failed", "Get notification click failed",
			"RS-NOT", "Notification section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_PROFILE_SUCCESS("RES-SER-314", SUCCESS, "Get profile: Success", "Get profile is Success", "RS-PROF",
			"Profile section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_PROFILE_FAILURE("RES-SER-315", FAILURE, "Get profile: Failed", "Get profile failed", "RS-PROF",
			"Profile section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	TRANSLITERATION_FAILURE("RES-SER-316", FAILURE, "Transliteration: Failed", "Transliteration failed", "RS-TRAN",
			"Transliteration section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	VERIFICATION_STATUS_SUCCESS("RES-SER-317", SUCCESS, "Verification status: Success",
			"Verification status is success", "RS-VER", "Verification section", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	VERIFICATION_STATUS_FAILURE("RES-SER-318", FAILURE, "Verification status: Failed", "Verification status is failed",
			"RS-VER", "Verification section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	REQ_EUIN_SUCCESS("RES-SER-319", SUCCESS, "Request EUIN: Success",
			"Requesting euin for transaction id %s is success", "RS-UIN", "UIN", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	DEACTIVATED_VID("RES-SER-320", SUCCESS, "Request to revoke VID",
			"Deactivated VID for transaction id %s while generating VID", "RS_VID_REV", "Revoke vid",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	AUTH_TYPE_CALL_BACK_SUCCESS("RES-SER-323", SUCCESS, "Auth type call back: Success",
			"auth type call back success for transaction id %s", "RS-AUTH_TYP", "Auth type", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	AUTH_TYPE_CALL_BACK_FAILURE("RES-SER-324", FAILURE, "Auth type call back: Failed",
			"auth type call back failure for transaction id %s", "RS-AUTH_TYP", "Auth type", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),

	BASE_EXCEPTION("RES-SER-401", FAILURE, "Base Exception", "Base exception for transaction id %s", "RS-EXCE",
			"Exception", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	REQUEST_FAILED("RES-SER-402", FAILURE, "Request failed", "Request failed for transaction id %s", "RS-REQ",
			"Request", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	SEND_NOTIFICATION_FAILURE("RES-SER-403", FAILURE, "Send notification: Failed",
			"Failure notification sent for transaction id %s", "RS-NOT", "Notification section",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	VID_JSON_PARSING_EXCEPTION("RES-SER-404", FAILURE, "Json parsing exception",
			"JSON parsing exception for transaction id %s while generating VID", "RS-VID", "VID section",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	VID_ALREADY_EXISTS("RES-SER-405", INFO, "VID already exists", "VID already exists for transaction id %s",
			"RS-VID_GEN", "VID generation", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	VID_GENERATION_FAILURE("RES-SER-406", FAILURE, "Request to generate VID: Failed",
			"VID generated failed for transaction id %s", "RS-VID_GEN", "VID generation", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	VID_REVOKE_EXCEPTION("RES-SER-407", FAILURE, "Request to revoke VID: Exception",
			"Revoking VID failed for transaction id %s", "RS_VID_REV", "Revoke vid", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	RID_NOT_FOUND("RES-SER-408", FAILURE, "Checking RID status: Not found",
			"RID not found while checking for RID status", "RS-RID", "RID section", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	TOKEN_GENERATION_FAILED("RES-SER-409", FAILURE, "Generating token: Failed", "Token generation failed", "RS-TOK",
			"Token generation", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	INPUT_INVALID("RES-SER-410", FAILURE, "Invalid input", "Invalid input parameter %s", "RS-VAL", "Validation section",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	API_NOT_AVAILABLE("RES-SER-411", FAILURE, "API not available", "API not available for transaction id %s", "RS-API",
			"API section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	API_RESOURCE_UNACCESS("RES-SER-412", FAILURE, "API resource unaccess",
			"Unable to access API resource for transaction id %s", "RS-API", "API section", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	RID_INVALID("RES-SER-413", FAILURE, "Check RID: Invalid", "RID is invalid", "RS-RID", "RID section",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	INPUT_DOESNT_EXISTS("RES-SER-414", FAILURE, "Validating request", "Request does not exists", "RS-VAL",
			"Validation section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	TEMPLATE_EXCEPTION("RES-SER-415", FAILURE, "Get template", "Template Exception", "RS-TEMP", "Template section",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	TEMPLATE_SUBJECT_EXCEPTION("RES-SER-416", FAILURE, "Get template Subject", "Template subject exception", "RS-TEMP",
			"Template section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	NOTIFICATION_FAILED("RES-SER-417", FAILURE, "Notification failed", "Notification failed for transaction id %s",
			"RS-NOT", "Notification section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	BAD_REQUEST("RES-SER-418", FAILURE, "Bad request", "Bad request", "RS-REQ", "Bad request", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	INVALID_API_RESPONSE("RES-SER-419", FAILURE, "Checking RID status: Invalid API response",
			"Invalid api response while checking RID status", "RS-API", "API section", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	IO_EXCEPTION("RES-SER-420", FAILURE, "IO Exception", "IO exception for transaction id %s", "RS-EXCE", "Exception",
			RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	JSON_PARSING_EXCEPTION("RES-SER-421", FAILURE, "Request for UIN update: Exception",
			"JSON parsing exception for transaction id %s", "RS-EXCE", "Exception", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	OTP_VALIDATION_FAILED("RES-SER-422", FAILURE, "OTP validation: Failed", "OTP validation failed for user Id: %s",
			"RS-OTP", "Otp section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	UNKNOWN_EXCEPTION("RES-SER-423", FAILURE, "Request to create packet: Exception", "Unknown exception occured",
			"RS-EXCE", "Exception", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	PACKET_CREATED_EXCEPTION("RES-SER-424", FAILURE, "Request to create packet: Exception",
			"Exception while creating packet", "RS-PACK", "Packet creation", RESIDENT_APPLICATION_ID,
			RESIDENT_APPLICATION_NAME),
	PACKET_CREATED_FAILURE("RES-SER-425", FAILURE, "Request to upload UIN packet: Failed", "Packet sync Failure",
			"RS-PACK", "Packet creation", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	UNSUPPORTED_INPUT("RES-SER-427", FAILURE, "Unsupported input", "Unsupported input parameter %s", "RS-VAL",
			"Validation section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	INVALID_PAGE_INDEX_VALUE("RES-SER-446", FAILURE, "Invalid page index value", "Invalid page index value %s",
			"RS-VAL", "Validation", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	INVALID_PAGE_SIZE_VALUE("RES-SER-447", FAILURE, "Invalid page size value", "Invalid page size value %s", "RS-VAL",
			"Validation", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	INVALID_LANGUAGE_CODE("RES-SER-500", FAILURE, "Invalid language code", "invalid lang code", "RS-VAL",
			"Validation section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_PENDING_DRAFT_SUCCESS("RES-SER-501", FAILURE, "Get pending draft success", "Get pending draft success", "RS-VAL",
			"Validation section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	GET_PENDING_DRAFT_FAILURE("RES-SER-502", FAILURE, "Get pending draft failure", "Get pending draft failure", "RS-VAL",
			"Validation section", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	DISCARD_DRAFT_SUCCESS("RES-SER-249", SUCCESS, "Discard Draft: Success",
			"Draft discarded successfully", "RS-DRAFT",
			"Discard draft", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME),
	DISCARD_DRAFT_EXCEPTION("RES-SER-250", FAILURE, "Discard Draft: Failed",
			"Draft discarded failed", "RS-DRAFT",
			"Discard draft", RESIDENT_APPLICATION_ID, RESIDENT_APPLICATION_NAME);

	private final String eventId;

	private final String type;

	private String name;

	private String description;

	private String moduleId;

	private String moduleName;

	private String applicationId;

	private String applicationName;

	private AuditEnum(String eventId, String type, String name, String description, String moduleId, String moduleName,
			String applicationId, String applicationName) {
		this.eventId = eventId;
		this.type = type;
		this.name = name;
		this.description = description;
		this.moduleId = moduleId;
		this.moduleName = moduleName;
		this.applicationId = applicationId;
		this.applicationName = applicationName;
	}

	@Override
	public String getEventId() {
		return eventId;
	}

	@Override
	public String getType() {
		return type;
	}

	@Override
	public String getName() {
		return name;
	}

	@Override
	public String getDescription() {
		return description;
	}

	@Override
	public String getModuleId() {
		return moduleId;
	}

	@Override
	public String getModuleName() {
		return moduleName;
	}

	@Override
	public String getApplicationId() {
		return applicationId;
	}

	@Override
	public String getApplicationName() {
		return applicationName;
	}

	/*
	 * Replace %s value in description with second parameter passed
	 */
	public static AuditEvent getAuditEventWithValue(AuditEnum auditEnum, String s) {
		AuditObject auditObject = auditEnum.createAuditObject();
		auditObject.setDescription(String.format(auditEnum.getDescription(), s));
		return auditObject;
	}

	/*
	 * Replace %s value in description with second parameter passed and name
	 * property of enum with third parameter
	 */
	public static AuditEvent getAuditEventWithValue(AuditEnum auditEnum, String edescription, String ename) {
		AuditObject auditObject = auditEnum.createAuditObject();
		auditObject.setDescription(String.format(auditEnum.getDescription(), edescription));
		auditObject.setName(String.format(auditEnum.getName(), ename));
		return auditObject;
	}

	private AuditObject createAuditObject() {
		return new AuditObject(eventId, type, name, description, moduleId, moduleName, applicationId, applicationName);
	}

}
