GetInputAttributeValues:
   Resident_GetInputAttributeValues1_UIN_all_Valid_Smoke:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      uniqueIdentifier: TC_Resident_GetInputAtributes_01      
      description: Verify that the system successfully returns input attribute values for update-demographics schema type when the API is called with valid input details and a valid UIN
      role: residentNew
      additionalDependencies: Dependent_ESignet_GenerateToken_01
      checkErrorsOnlyInResponse: true
      restMethod: get
      auditLogCheck: true
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/GetInputAttributeValues/getInputAttributeValuesResult
      input: '{
      	"schemaType":"update-demographics"
}'
      output: '{
}'

   Resident_GetInputAttributeValues2_UIN_all_Valid_Smoke:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      uniqueIdentifier: TC_Resident_GetInputAtributes_02      
      description: Verify that the system successfully returns input attribute values for share-credential schema type when the API is called with valid input details and a valid UIN
      role: residentNew
      checkErrorsOnlyInResponse: true
      additionalDependencies: Dependent_ESignet_GenerateToken_01
      restMethod: get
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/GetInputAttributeValues/getInputAttributeValuesResult
      input: '{
      	"schemaType":"share-credential"
}'
      output: '{
}'

   Resident_GetInputAttributeValues3_UIN_all_Valid_Smoke:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      uniqueIdentifier: TC_Resident_GetInputAtributes_03      
      description: Verify that the system successfully returns input attribute values for personalized-card schema type when the API is called with valid input details and a valid UIN
      role: residentNew
      checkErrorsOnlyInResponse: true
      additionalDependencies: Dependent_ESignet_GenerateToken_01
      restMethod: get
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/GetInputAttributeValues/getInputAttributeValuesResult
      input: '{
      	"schemaType":"personalized-card"
}'
      output: '{
}'

   Resident_GetInputAttributeValues_UIN_Invalid_SchemaType_Neg:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      uniqueIdentifier: TC_Resident_GetInputAtributes_04      
      description: Verify that the system returns an error when the API is called with a valid UIN and an invalid schema type
      role: residentNew
      checkErrorsOnlyInResponse: true
      additionalDependencies: Dependent_ESignet_GenerateToken_01
      restMethod: get
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/error
      input: '{
      	"schemaType":"#$$#$#"
}'
      output: '{
	"errors": [
    {
      "errorCode": "RES-SER-410"
    }
  ]
}'

   Resident_GetInputAttributeValues1_Vid_all_Valid_Smoke:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      uniqueIdentifier: TC_Resident_GetInputAtributes_05      
      description: Verify that the system successfully returns the input attribute values when the API is called with valid input details and a valid VID
      role: residentNewVid
      checkErrorsOnlyInResponse: true
      additionalDependencies: Dependent_ESignet_GenerateToken_02
      restMethod: get
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/GetInputAttributeValues/getInputAttributeValuesResult
      input: '{
      	"schemaType":"update-demographics"
}'
      output: '{
}'

   Resident_GetInputAttributeValues2_Vid_all_Valid_Smoke:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      uniqueIdentifier: TC_Resident_GetInputAtributes_05      
      description: Verify that the system successfully returns the second input attribute values using a valid vid with all valid inputs when the API is called with valid input details and a valid VID
      role: residentNewVid
      checkErrorsOnlyInResponse: true
      additionalDependencies: Dependent_ESignet_GenerateToken_02
      restMethod: get
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/GetInputAttributeValues/getInputAttributeValuesResult
      input: '{
      	"schemaType":"share-credential"
}'
      output: '{
}'

   Resident_GetInputAttributeValues3_Vid_all_Valid_Smoke:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      uniqueIdentifier: TC_Resident_GetInputAtributes_06      
      description: Verify that the system successfully returns the third input attribute values using a valid vid with all valid inputs when the API is called with valid input details and a valid VID
      role: residentNewVid
      checkErrorsOnlyInResponse: true
      additionalDependencies: Dependent_ESignet_GenerateToken_02
      restMethod: get
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/GetInputAttributeValues/getInputAttributeValuesResult
      input: '{
      	"schemaType":"personalized-card"
}'
      output: '{
}'