GetInputAttributeValues:
   Resident_GetInputAttributeValues1_UIN_all_Valid_Smoke:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      uniqueIdentifier: TC_Resident_GetInputAtributes_01      
      description: Get input attribute values using a valid UIN with all valid inputs
      role: residentNew
      checkErrorsOnlyInResponse: true
      restMethod: get
      auditLogCheck: true
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/GetInputAttributeValues/getInputAttributeValuesResult
      input: '{
      	"schemaType":"update-demographics"
}'
      output: '{
}'

   Resident_GetInputAttributeValues2_UIN_all_Valid_Smoke:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      uniqueIdentifier: TC_Resident_GetInputAtributes_02      
      description: Get second input attribute values using a valid UIN with all valid inputs
      role: residentNew
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/GetInputAttributeValues/getInputAttributeValuesResult
      input: '{
      	"schemaType":"share-credential"
}'
      output: '{
}'

   Resident_GetInputAttributeValues3_UIN_all_Valid_Smoke:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      uniqueIdentifier: TC_Resident_GetInputAtributes_03      
      description: Get third input attribute values using a valid UIN with all valid inputs
      role: residentNew
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/GetInputAttributeValues/getInputAttributeValuesResult
      input: '{
      	"schemaType":"personalized-card"
}'
      output: '{
}'

   Resident_GetInputAttributeValues_UIN_Invalid_SchemaType_Neg:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      uniqueIdentifier: TC_Resident_GetInputAtributes_04      
      description: Get input attribute values using a valid UIN with an invalid schematype
      role: residentNew
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/error
      input: '{
      	"schemaType":"#$$#$#"
}'
      output: '{
	"errors": [
    {
      "errorCode": "RES-SER-410",
      "message": "$IGNORE$"
    }
  ]
}'

   Resident_GetInputAttributeValues1_Vid_all_Valid_Smoke:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      uniqueIdentifier: TC_Resident_GetInputAtributes_05      
      description: Get input attribute values using a valid VID with all valid inputs
      role: residentNewVid
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/GetInputAttributeValues/getInputAttributeValuesResult
      input: '{
      	"schemaType":"update-demographics"
}'
      output: '{
}'

   Resident_GetInputAttributeValues2_Vid_all_Valid_Smoke:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      uniqueIdentifier: TC_Resident_GetInputAtributes_05      
      description: Get second input attribute values using a valid VID with all valid inputs
      role: residentNewVid
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/GetInputAttributeValues/getInputAttributeValuesResult
      input: '{
      	"schemaType":"share-credential"
}'
      output: '{
}'

   Resident_GetInputAttributeValues3_Vid_all_Valid_Smoke:
      endPoint: /resident/v1/identity/info/type/{schemaType}
      uniqueIdentifier: TC_Resident_GetInputAtributes_06      
      description: Get third input attribute values using a valid VID with all valid inputs
      role: residentNewVid
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: resident/GetInputAttributeValues/getInputAttributeValues
      outputTemplate: resident/GetInputAttributeValues/getInputAttributeValuesResult
      input: '{
      	"schemaType":"personalized-card"
}'
      output: '{
}'